language: node_js

node_js:
  - "12"
  - "10"
  - "8"

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: test
      script: "npm run test:es5"
      script: npm run test
      script: "npm run test:perf"
    - stage: build_docs
      before_script: cd website
      script: npm install && npm run build

after_success:
  - codecov

cache:
  directories:
    - "$HOME/.npm"
